SPACESHIP_GIT_STATUS_STASHED=""
SPACESHIP_AWS_SYMBOL="  "
SPACESHIP_AWS_PREFIX=""
SPACESHIP_NODE_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_DOCKER_COMPOSE_SHOW=false
